#!/bin/bash
./gradlew cardsgen:shadowJar
spark-submit --master "local[$1]" --class com.hiddenswitch.cardsgen.applications.ControlApplication cardsgen/build/libs/cardsgen-1.2.0-all.jar -output $2 -gamesperbatch $3 -batches $4
