package net.demilich.metastone.game.targeting;

public enum TargetSelection {
	NONE,
	ENEMY_CHARACTERS,
	ENEMY_MINIONS,
	ENEMY_HERO,
	ENEMY_PLAYER,
	FRIENDLY_CHARACTERS,
	FRIENDLY_MINIONS,
	FRIENDLY_HERO,
	FRIENDLY_PLAYER,
	MINIONS,
	HEROES,
	ADJACENT_MINIONS,
	ANY
}
