package net.demilich.metastone.game.spells.desc;

public enum SpellArg {

	CLASS, MIN_DAMAGE, MAX_DAMAGE, VALUE, SECONDARY_VALUE, TARGET, SPELL_SOURCE, CARD_COST_MODIFIER, SECRET, TRIGGER, ATTRIBUTE, REVERT_TRIGGER, SECOND_REVERT_TRIGGER, ATTACK_BONUS, HP_BONUS, ARMOR_BONUS, VALUE_PROVIDER, ATTACK_VALUE_PROVIDER, HP_VALUE_PROVIDER, HERO_POWER, CARD_LOCATION, HOW_MANY, FILTER, CARD_FILTER, CARD_PROCESSOR, CARD_PROVIDER, TARGET_PLAYER, SPELL_CONDITION_CHECKER, SPELL_1, SPELL_2, SPELL_3, UNIQUE_MINION, RACE, CARD, CARDS, ENTITY, RANDOM_TARGET, BOARD_POSITION_ABSOLUTE, BOARD_POSITION_RELATIVE, FULL_MANA_CRYSTALS, MANA_MODIFIER, CONDITION, EXCLUSIVE
}
