package net.demilich.metastone.game.behaviour.threat;

public enum WeightedFeature {
	RED_MODIFIER, YELLOW_MODIFIER, OWN_HP_FACTOR, OPPONENT_HP_FACTOR, OWN_CARD_COUNT, OPPONENT_CARD_COUNT, MINION_INTRINSIC_VALUE, MINION_ATTACK_FACTOR, MINION_HP_FACTOR, MINION_RED_TAUNT_MODIFIER, MINION_YELLOW_TAUNT_MODIFIER, MINION_DEFAULT_TAUNT_MODIFIER, MINION_WINDFURY_MODIFIER, MINION_DIVINE_SHIELD_MODIFIER, MINION_SPELL_POWER_MODIFIER, MINION_STEALTHED_MODIFIER, MINION_UNTARGETABLE_BY_SPELLS_MODIFIER, HARD_REMOVAL_VALUE
}
