package net.demilich.metastone.game.behaviour.heuristic;

public enum WeightedFeature {
	HP_DIFFERENCE, CARD_DIFFERENCE, OWN_MINION_COUNT, OPPONENT_MINION_COUNT, MINION_ATTACK, MINION_HP, MINION_TAUNT, MINION_WINDFURY, MINION_DIVINE_SHIELD, MINION_SPELL_POWER, MINION_UNTARGETABLE_BY_SPELLS, MINION_STEALTHED,
}
