package net.pferdimanzug.hearthstone.analyzer.game.events;

public enum GameEventType {
	ALL,
	DAMAGE,
	SUMMON,
	HEAL,
	KILL,
	PHYSICAL_ATTACK,
	TURN_START,
	TURN_END,
	SPELL_CASTED,
	OVERLOAD,
	RECEIVE_CARD,
	PLAY_CARD,
	TARGET_ACQUISITION,
	SECRET_PLAYED,
	SECRET_REVEALED,
	SILENCE,
	WEAPON_DESTROYED,
	BOARD_CHANGED,
	ARMOR_GAINED
}
