package net.demilich.metastone.game.statistics;

public enum Statistic {
	// meta statistics
	WIN_RATE,
	// AVG_TURNS_TAKEN,

	GAMES_WON,
	GAMES_LOST,
	DAMAGE_DEALT,
	HEALING_DONE,
	MANA_SPENT,
	CARDS_PLAYED,
	TURNS_TAKEN,
	ARMOR_GAINED,
	CARDS_DRAWN,
	FATIGUE_DAMAGE,
	MINIONS_PLAYED,
	SPELLS_CAST,
	HERO_POWER_USED,
	WEAPONS_EQUIPPED,
	WEAPONS_PLAYED,

}
