package net.demilich.metastone.game.spells.desc.trigger;

public enum EventTriggerArg {
	CLASS,
	TARGET_PLAYER,
	SOURCE_PLAYER,
	CARD_TYPE,
	SOURCE_TYPE,
	WORKS_ON_HERO,
	SOURCE_ENTITY_TYPE,
	TARGET_ENTITY_TYPE,
	RACE,
	ACTION_TYPE,
	OWN_TURN_ONLY,
	HOST_TARGET_TYPE,
	ATTACKER_ONLY,
	BREAKS_STEALTH,
	REQUIRED_ATTRIBUTE,
	CONDITION,
	TARGET
}
