package net.demilich.metastone.game.cards.desc;

public enum ParseValueType {
	BOOLEAN,
	INTEGER,
	TARGET_REFERENCE,
	TARGET_PLAYER,
	RACE,
	SPELL,
	ATTRIBUTE,
	VALUE_PROVIDER,
	ENTITY_FILTER,
	STRING,
	STRING_ARRAY,
	BOARD_POSITION_RELATIVE,
	CARD_LOCATION,
	OPERATION,
	ALGEBRAIC_OPERATION,
	CONDITION,
	CARD_TYPE,
	ENTITY_TYPE,
	ACTION_TYPE,
	TRIGGER,
	EVENT_TRIGGER,
	CARD_COST_MODIFIER,
	RARITY,
	HERO_CLASS
}
