package net.demilich.metastone.game;

public enum Environment {
	SUMMON_REFERENCE_STACK,
	SUMMONED_WEAPON,
	KILLED_MINION,
	PENDING_CARD,
	TARGET_OVERRIDE,
	ATTACKER,
	EVENT_TARGET_STACK,
	TARGET,
	TRANSFORM_REFERENCE,
	DAMAGE_STACK,
	DEBUG
}
