package net.demilich.metastone.game;

public enum Environment {
	SUMMON_REFERENCE_STACK,
	KILLED_MINION,
	TARGET_OVERRIDE,
	ATTACKER_REFERENCE,
	EVENT_TARGET_REFERENCE_STACK,
	TARGET,
	TRANSFORM_REFERENCE,
	DAMAGE_STACK,
	DEBUG,
	PENDING_CARD
}
