package com.hiddenswitch.proto3.net.common;

public enum MessageType {
	REGISTER_PLAYER,
	UPDATE_ACTION,
	ON_GAME_EVENT,
	ON_GAME_END,
	SET_PLAYERS,
	ON_ACTIVE_PLAYER,
	ON_UPDATE,
	ON_TURN_END,
	ON_REQUEST_ACTION,
	FIRST_MESSAGE,
	ON_MULLIGAN,
	UPDATE_MULLIGAN
}
